language: r
cache: packages

before_install:
  - sudo apt-get install libgdal1-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev libudunits2-dev libgit2-dev mesa-common-dev

install:
  - R -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'
  - R -e 'devtools::install_github("James-Thorson-NOAA/VAST", INSTALL_opts="--no-staged-install")'
  - R -e 'devtools::install_github("James-Thorson-NOAA/FishStatsUtils", INSTALL_opts="--no-staged-install")'
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R -e 'devtools::check(cran=FALSE)'

r_github_packages:
  - James-Thorson-NOAA/VAST
  - James-Thorson-NOAA/FishStatsUtils
  - kaskr/TMB_contrib_R/TMBhelper

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change