language: r
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  -R -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'
  -R -e 'install.packages("devtools")'
  -R -e 'devtools::install_github("James-Thorson-NOAA/VAST", INSTALL_opts="--no-staged-install")'
  -R -e 'devtools::install_github("James-Thorson-NOAA/FishStatsUtils", INSTALL_opts="--no-staged-install")'

r_github_packages:
  - James-Thorson-NOAA/VAST
  - James-Thorson-NOAA/FishStatsUtils
  - kaskr/TMB_contrib_R/TMBhelper

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change